export const REGISTER_INFO = {
  ORDER_NUMBER: 0,
  GUEST_NAME: 1,
  GUEST_EMAIL: 2,
  GUEST_PHONE: 3,
  GUEST_TICKET_AMOUNT: 4,
  GUEST_TOTAL_MONEY: 5,
  GUEST_TRANSFER_PAYMENT: 6,
  SEND_GUEST_EMAIL_PAYMENT: 7,
};

export const EVENT_INFO = {
  EVENT_ID: 0,
  EVENT_NAME: 1,
  EVENT_DATE: 2,
  EVENT_SHORT_DESC: 3,
  EVENT_LONG_DESC: 4,
  EVENT_PRICE: 5,
  EVENT_THUMBNAIL: 6,
  EVENT_TICKET_AMOUNT: 7,
  BANK: 8,
  ACCOUNT_NUMBER: 9,
  LOCATION: 10,
  PHONE_SUPPORT: 11,
  EMAIL_SUPPORT: 12,
  AMOUNT_TICKET_LEFTS: 13,
  EVENT_GENRE: 14,
  EVENT_TIME_START: 15,
};
